### ISSUE TITLE
Legacy BMX, MinGW 4.8.1 building tools/wxCodegen

### ISSUE THREAD

**Issue by olejr** [maxmods/wx.mod#5]
Getting some lines of:
BlitzMax/mod/wx.mod/wx.mod/../lib/win32/libwxmsw30u_xrc.a(xrclib_xmlres.o):xmlres.cpp:(.text+0x9a23): undefined reference to `_time32'

And then:

C:/Programming/BlitzMax/bin/ld.exe: C:/Programming/BlitzMax/mod/wx.mod/wx.mod/../lib/win32/libwxmsw30u_xrc.a(xrclib_xmlres.o): bad reloc address 0x2 in section `.text$_ZN20wxXmlSubclassFactoryD1Ev[__ZN20wxXmlSubclassFactoryD1Ev]'

Don't know if this is the fault of wx.mod, bah.mod/libxml.mod or the wxCodegen tool.

Can't test it on bmx-ng, as libxml.mod (more or less expected) fail to compile with an:
Internal Error.
[mod/bah.mod/libxml.mod/.bmx/common.bmx.debug.win32.x86.i;165;0]

**Comment by woollybah** [comment]
Legacy BlitzMax now requires to build with mingw-w64 7.2.0 rev 1 to work with the latest wxMax libs.
